### ISSUE TITLE
Development VPC

### ISSUE THREAD

**Issue by frankgibbs** [aws-quickstart/quickstart-compliance-pci#2]
Let me know if I should be asking this question somewhere else.

I understand the notional Development VPC isn't implemented in this template. However if were to be implemented what is the suggested approach?

My inclination is to duplicate vpn-production and name it vpc-development and prefix resources with development instead of production.

**Comment by andrew-glenn** [comment]
@frankgibbs  - Apologies for the delay. I think that'd be the most straight-forward approach, and what I would suggest. I'm approaching it from the angle that development and production infrastructure should (ideally) mirror each other when possible.
